meta_product_name: 'Furry Friend'

meta_title: 'FurryFriends - Your donations never end'

meta_description: 'A place where you can financially support animal shelters and have great time with a virtual pet!'

meta_image: 'frame og.png' # should exist in `app/assets/images/`
